name: Feature Request
description: Request a feature to be added to this project
title: "[Feature Request] "
labels: ["Feature Request"]
 
 body:
  - type: markdown
    attributes:
      Value: |
        Thanks for requesting a new feature!
    - type: input
      id: contact
      attributes:
        label: Contact Details
        description: How can we get in contact with you for more information?
        placeholder: ex. email@example.com
      validations:
        required: true
    - type: dropdown
      id: request-type
      attributes:
        label: Is this a hardware or software request?
         multiple: false
         options:
          - Hardware
          - Software
    - type: textarea
      id: version
      attributes:
        label: Version
        description: What version/Branch of this repo are you using?
        value: "CommitID/Branch"
    - type: textarea
      id: describe
      attrubutes: Describe the feature
        description: Also tell us, do you have any ideas towards the designing and creation of this feature?
        placeholder: Information Here!
      validation:
        required: true
      
